### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by quasiperfect** [peterbe/minimalcss#231] opened 2018-07-02 11:46 UTC
hi

what could trigger that error ?

i got this issue testing on http://codingheads.com/

**Comment by stereobooster** [comment] 2018-07-02 18:40
Caused by:

```
@-moz-document url-prefix() {
	inputtype:radio],input[type=checkbox]{vertical-align:middle;
	margin-top:-.3em
}
}
```

Which is parsed to

```
{ type: 'Raw',
  loc: null,
  value: 'inputtype:radio],input[type=checkbox]' }
```

**Comment by quasiperfect** [comment] 2018-07-03 06:03
@stereobooster thanks for your help. that would be great(handle invalid CSS)

**Comment by harrygreen** [comment] 2018-07-25 14:40
This error actually found a ton of invalid crap in our production CSS!

**Comment by stereobooster** [comment] 2018-08-08 17:35
fixed in #237

**Closed by stereobooster** 2018-08-08 17:35 UTC
Labels: bug
